import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import styles from "./layout.module.css";
import "./main.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "900"] });

export const metadata: Metadata = {
  title: "Learning Pathway for Exceptional Learners",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className={styles.pageContainer}>
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
